/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package First_GUI;

/**
 *
 * @author syari
 */
public class comboBox extends javax.swing.JFrame {

    /**
     * Creates new form comboBox
     */
    public comboBox() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboBoxDomisili = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboBoxKota = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        comboBoxDesa = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        comboBoxDomisili.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jawa Tengah", "Jawa Timur", "Jawa Barat" }));
        comboBoxDomisili.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxDomisiliActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Pilih Domisili :");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Pilih Kota       :");

        comboBoxKota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxKotaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Pilih Desa       :");

        comboBoxDesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxDesaActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/loginuser-removebg-preview.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboBoxDesa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboBoxDomisili, 0, 114, Short.MAX_VALUE)
                            .addComponent(comboBoxKota, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxDomisili, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxKota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxDesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxKotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxKotaActionPerformed
        // TODO add your handling code here:
    String kota = (String) comboBoxKota.getSelectedItem();
    comboBoxDesa.removeAllItems();  // Kosongkan dulu

    if(kota == null) return;  // antisipasi null jika belum ada item

    switch(kota) {
        case "Jepara":
        comboBoxDesa.addItem("Desa Bawu");
        comboBoxDesa.addItem("Desa Krapyak");
        comboBoxDesa.addItem("Desa Mulyoharjo");
            break;
        case "Semarang":
            comboBoxDesa.addItem("Desa Banyumanik");
            comboBoxDesa.addItem("Desa Tembalang");
            comboBoxDesa.addItem("Desa Ngaliyan");
            break;
        case "Kudus":
            comboBoxDesa.addItem("Desa Kaliwungu");
            comboBoxDesa.addItem("Desa Jati Wetan");
            comboBoxDesa.addItem("Desa Panjang");
            break;
        case "Bandung":
            comboBoxDesa.addItem("Desa Bojongsoang");
            comboBoxDesa.addItem("Desa Cibiru");
            comboBoxDesa.addItem("Desa Cipadung");
            break;
        case "Bogor":
            comboBoxDesa.addItem("Desa Cibinong");
            comboBoxDesa.addItem("Desa Dramaga");
            comboBoxDesa.addItem("Desa Ciomas");
            break;
        case "Bekasi":
            comboBoxDesa.addItem("Desa Cibitung");
            comboBoxDesa.addItem("Desa Babelan");
            comboBoxDesa.addItem("Desa Tambun");
            break;
        case "Surabaya":
            comboBoxDesa.addItem("Desa Wonokromo");
            comboBoxDesa.addItem("Desa Rungkut");
            comboBoxDesa.addItem("Desa Tambaksari");
            break;
        case "Malang":
            comboBoxDesa.addItem("Desa Lowokwaru");
            comboBoxDesa.addItem("Desa Sukun");
            comboBoxDesa.addItem("Desa Blimbing");
            break;
        case "Kediri":
            comboBoxDesa.addItem("Desa Pare");
            comboBoxDesa.addItem("Desa Banyakan");
            comboBoxDesa.addItem("Desa Wates");
            break;
        default:
            comboBoxDesa.addItem("Pilih desa...");
            break;
        // dst...
    }
    }//GEN-LAST:event_comboBoxKotaActionPerformed

    private void comboBoxDomisiliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxDomisiliActionPerformed
        // TODO add your handling code here:
        String domisili = comboBoxDomisili.getSelectedItem().toString();
        comboBoxKota.removeAllItems(); // kosongkan dulu kota

        if(domisili.equals("Jawa Tengah")) {
            comboBoxKota.addItem("Jepara");
            comboBoxKota.addItem("Semarang");
            comboBoxKota.addItem("Kudus");
            comboBoxKota.addItem("Solo");
        } else if(domisili.equals("Jawa Barat")) {
            comboBoxKota.addItem("Bandung");
            comboBoxKota.addItem("Bogor");
            comboBoxKota.addItem("Bekasi");
        } else if(domisili.equals("Jawa Timur")) {
            comboBoxKota.addItem("Surabaya");
            comboBoxKota.addItem("Malang");
            comboBoxKota.addItem("Kediri");
        }
    }//GEN-LAST:event_comboBoxDomisiliActionPerformed

    private void comboBoxDesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxDesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxDesaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(comboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(comboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(comboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(comboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new comboBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBoxDesa;
    private javax.swing.JComboBox<String> comboBoxDomisili;
    private javax.swing.JComboBox<String> comboBoxKota;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
