/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIDB;

import java.sql.*;
import javax.swing.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSetMetaData;
import java.awt.*;
/**
 *
 * @author User ID
 */
public class TampilkanData extends javax.swing.JFrame {
    DefaultTableModel model;
    JTable tabel;
    /**
     * Creates new form TampilkanData
     */
    public TampilkanData() {
        initComponents();
        setTitle("Data dosen");
        setSize(600, 400);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        
        model = new DefaultTableModel();
        tabel = new JTable(model); 
        setLayout(new BorderLayout());
        JScrollPane scrollPane = new JScrollPane(tabel);
        add(new JScrollPane(tabel));
        //add(scrollPane, BorderLayout.CENTER);
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void loadData() {
        String url = "jdbc:mysql://localhost:3307/2023_akademik";
        String user ="root";
        String pass = "";
        try (Connection conn = DriverManager.getConnection(url, user, pass)){
            Statement stmt =conn.createStatement(); 
            ResultSet rs = stmt.executeQuery("SELECT * FROM DOSEN");  
            ResultSetMetaData meta = rs.getMetaData();
            int kolom = meta.getColumnCount();
            // Tambah nama kolom ke model
            for (int i = 1; i <= kolom; i++) {
                model.addColumn(meta.getColumnName(i));
            }
            //tmbah data baris ke model
            while (rs.next()) {
                Object[] rowData = new Object[kolom];
                for (int i = 1; i <= kolom; i++) {
                    rowData[i - 1] = rs.getObject(i);
                }
                model.addRow(rowData);
            } 
            rs.close();
            stmt.close();
            conn.close();
            //System.out.println("Jumlah baris dalam model: " + model.getRowCount());
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal koneksi: " + e.getMessage());
        }
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TampilkanData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TampilkanData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TampilkanData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TampilkanData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        //SwingUtilities.invokeLater(() -> new TampilkanData().setVisible(true));
        java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new TampilkanData().setVisible(true);
         }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
