/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UAS;


import java.awt.Color;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author syari
 */
public class FrmAlatLab extends javax.swing.JFrame {
    private final DefaultTableModel model = null;
    
    /**
     * Creates new form FrmListRequest
     */
    
    
    
    public FrmAlatLab() {
        initComponents();
        setInitialState();
        TampilData();
        countData();
    }
    
    private void setInitialState() {
        btnedit.setEnabled(false);
        btnhapus.setEnabled(false);
        btnadd.setEnabled(true);

        txtKode.setEnabled(false);
        txtNama.setEnabled(false);
        cmbPJLab.setEnabled(false);
        cmbKategori.setEnabled(false);
        txtSatuan.setEnabled(false);
        txtJumlah.setEnabled(false);

        btnsave.setEnabled(false);
        btncancel.setEnabled(false);
    }
    
    private void countData() {
        DefaultTableModel model = (DefaultTableModel) daftarAlat.getModel();
        int rowCount = model.getRowCount();
        lblJumlah.setText("Jumlah Data: " + rowCount);
    }

    private void clearForm() {
        txtKode.setText("");
        txtNama.setText("");
        txtSatuan.setText("");
        txtJumlah.setText("");
        cmbKategori.setSelectedIndex(0); // atau setSelectedItem("Pilih...")
        cmbPJLab.setSelectedIndex(0);

        txtKode.setEnabled(false);
        txtNama.setEnabled(false);
        txtSatuan.setEnabled(false);
        txtJumlah.setEnabled(false);
        cmbKategori.setEnabled(false);
        cmbPJLab.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        daftarAlat = new javax.swing.JTable();
        panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtKode = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        cmbKategori = new javax.swing.JComboBox<>();
        txtSatuan = new javax.swing.JTextField();
        txtJumlah = new javax.swing.JTextField();
        btncancel = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        cmbPJLab = new javax.swing.JComboBox<>();
        lbl_action = new javax.swing.JLabel();
        btnadd = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        lblJumlah = new javax.swing.JLabel();
        btnkembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));

        jPanel1.setBackground(new java.awt.Color(0, 153, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Daftar Alat Laboratorium TI");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        daftarAlat.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        daftarAlat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Kode", "Nama", "Username", "Kategori", "Satuan", "Jumlah"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        daftarAlat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                daftarAlatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(daftarAlat);

        panel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        panel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel.setEnabled(false);

        jLabel3.setText("Kode");

        jLabel4.setText("Nama");

        jLabel5.setText("Kategori");

        jLabel6.setText("Satuan");

        jLabel7.setText("Jumlah");

        txtKode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKodeActionPerformed(evt);
            }
        });

        cmbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih Kategori-", "U-TakeOut", "NU-TakeOut" }));

        btncancel.setBackground(new java.awt.Color(255, 51, 51));
        btncancel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btncancel.setForeground(new java.awt.Color(255, 255, 255));
        btncancel.setText("Batal");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });

        btnsave.setBackground(new java.awt.Color(0, 204, 0));
        btnsave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnsave.setForeground(new java.awt.Color(255, 255, 255));
        btnsave.setText("Simpan");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        jLabel9.setText("Username");

        cmbPJLab.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih PJ Lab-", "32089000645", "32089000646", "32089000647", "32089000678" }));
        cmbPJLab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPJLabActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(btncancel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnsave, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                            .addComponent(txtKode)
                            .addComponent(txtNama)
                            .addComponent(txtSatuan)
                            .addComponent(txtJumlah)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(cmbKategori, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(60, 60, 60))))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(cmbPJLab, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cmbPJLab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncancel)
                    .addComponent(btnsave))
                .addGap(14, 14, 14))
        );

        lbl_action.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_action.setText("Tambah Data");

        btnadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add.png"))); // NOI18N
        btnadd.setText("Tambah");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit.png"))); // NOI18N
        btnedit.setText("Ubah");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnhapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete.png"))); // NOI18N
        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/reload.png"))); // NOI18N

        lblJumlah.setText("Jumlah Data");

        btnkembali.setText("Kembali");
        btnkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblJumlah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnkembali))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnedit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnhapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_action)
                                .addGap(120, 120, 120)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lbl_action))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnadd)
                                .addComponent(btnedit)
                                .addComponent(btnhapus)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJumlah)
                    .addComponent(btnkembali))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtKodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKodeActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
        clearForm();          // Bersihkan semua inputan form
        setInitialState();
    }//GEN-LAST:event_btncancelActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        if (isEditMode) {
            int row = daftarAlat.getSelectedRow();
            if (row >= 0) {
                DefaultTableModel model = (DefaultTableModel) daftarAlat.getModel();
                String kodeAlatLama = model.getValueAt(row, 0).toString(); // Ambil kode_alat lama (yang jadi acuan UPDATE)

                // Update ke database
                try {
                    String sql = "UPDATE alat_lab SET "
                               + "kode_alat = ?, "
                               + "nama = ?, "
                               + "username = ?, "
                               + "kode_kategori = ?, "
                               + "satuan = ?, "
                               + "jumlah = ? "
                               + "WHERE kode_alat = ?";

                    Connection conn = (Connection) koneksi.GetConnection();
                    PreparedStatement pstm = conn.prepareStatement(sql);
                    pstm.setString(1, txtKode.getText());
                    pstm.setString(2, txtNama.getText());
                    pstm.setString(3, cmbPJLab.getSelectedItem().toString());
                    pstm.setString(4, cmbKategori.getSelectedItem().toString());
                    pstm.setString(5, txtSatuan.getText());
                    pstm.setString(6, txtJumlah.getText());
                    pstm.setString(7, kodeAlatLama); // Digunakan untuk WHERE

                    int affectedRows = pstm.executeUpdate();
                    pstm.close();
                    conn.close();

                    if (affectedRows > 0) {
                        // Update juga di tabel UI
                        model.setValueAt(txtKode.getText(), row, 0);
                        model.setValueAt(txtNama.getText(), row, 1);
                        model.setValueAt(cmbKategori.getSelectedItem().toString(), row, 2);
                        model.setValueAt(txtSatuan.getText(), row, 3);
                        model.setValueAt(txtJumlah.getText(), row, 4);

                        JOptionPane.showMessageDialog(this, "Data berhasil diubah.");
                    } else {
                        JOptionPane.showMessageDialog(this, "Gagal mengubah data di database.");
                    }

                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, "Kesalahan database: " + e.getMessage());
                }
            }

        } else {
            // logika untuk tambah data baru
            try {
                String sql = "INSERT INTO alat_lab(kode_alat, nama, username, kode_kategori, satuan, jumlah) VALUES ('"
                            + txtKode.getText() + "','"
                            + txtNama.getText() + "','"
                            + cmbPJLab.getSelectedItem().toString() + "','"
                            + cmbKategori.getSelectedItem().toString() + "','"
                            + txtSatuan.getText() + "','"
                            + txtJumlah.getText() + "')";

                java.sql.Connection conn = (Connection)koneksi.GetConnection();
                java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
                pstm.execute();
                pstm.close();
                conn.close();
                JOptionPane.showMessageDialog(null, "Proses tambah data berhasil");
            }
            catch (SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }

        // Reset form
        clearForm();
        btnsave.setText("Simpan");
        isEditMode = false;
        countData(); // update jumlah
        setInitialState(); // reset ke kondisi awal

    }//GEN-LAST:event_btnsaveActionPerformed

    private void cmbPJLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPJLabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPJLabActionPerformed

    private boolean isEditMode = false;
    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        int row = daftarAlat.getSelectedRow();
        if (row >= 0) {
            // Ambil data dari tabel
            DefaultTableModel model = (DefaultTableModel) daftarAlat.getModel();
            txtKode.setText(model.getValueAt(row, 0).toString());
            txtNama.setText(model.getValueAt(row, 1).toString());
            cmbPJLab.setSelectedItem(model.getValueAt(row, 2).toString());
            cmbKategori.setSelectedItem(model.getValueAt(row, 3).toString());
            txtSatuan.setText(model.getValueAt(row, 4).toString());
            txtJumlah.setText(model.getValueAt(row, 5).toString());

            // Aktifkan input
            txtKode.setEnabled(false);
            txtNama.setEnabled(true);
            cmbPJLab.setEnabled(true);
            cmbKategori.setEnabled(true);
            txtSatuan.setEnabled(true);
            txtJumlah.setEnabled(true);
            btnsave.setEnabled(true);
            btncancel.setEnabled(true);

            // Ubah state dan label
            isEditMode = true;
            lbl_action.setText("Edit Data");
            btnsave.setText("Edit");
            btnsave.setBackground(Color.YELLOW); // ubah latar belakang jadi kuning
            btnsave.setForeground(Color.BLACK);  // agar teks tetap terbaca
        }
    }//GEN-LAST:event_btneditActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        // Aktifkan input form
        txtKode.setEnabled(true);
        txtNama.setEnabled(true);
        cmbPJLab.setEnabled(true);
        cmbKategori.setEnabled(true);
        txtSatuan.setEnabled(true);
        txtJumlah.setEnabled(true);
        btnsave.setEnabled(true);
        btncancel.setEnabled(true);

        // Judul
        lbl_action.setText("Tambah Data");

        // Disable buttons lainnya
        btnedit.setEnabled(false);
        btnhapus.setEnabled(false);
        btnadd.setEnabled(true);
    }//GEN-LAST:event_btnaddActionPerformed

    private void daftarAlatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_daftarAlatMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        int row = daftarAlat.getSelectedRow();
        if (row >= 0) {
            btnedit.setEnabled(true);
            btnhapus.setEnabled(true);
            btnadd.setEnabled(false);
        }
    }//GEN-LAST:event_daftarAlatMouseClicked

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        int row = daftarAlat.getSelectedRow();
        if (row >= 0) {
            int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus data ini?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                DefaultTableModel model = (DefaultTableModel) daftarAlat.getModel();
                String idAlat = model.getValueAt(row, 0).toString(); // kolom pertama adalah kode_alat

                try {
                    java.sql.Connection conn = koneksi.GetConnection();

                    // Cek apakah alat sedang dipinjam (status = 'dipinjam')
                    String cekQuery = "SELECT COUNT(*) FROM transaksi_peminjaman WHERE kode_alat = ?";
                    PreparedStatement cekStmt = conn.prepareStatement(cekQuery);
                    cekStmt.setString(1, idAlat);
                    ResultSet rs = cekStmt.executeQuery();

                    if (rs.next() && rs.getInt(1) > 0) {
                        // Jika alat sedang dipinjam
                        JOptionPane.showMessageDialog(this, "Alat sedang diproses di transaksi peminjaman dan tidak bisa dihapus.");
                    } else {
                        // Jika tidak sedang dipinjam, lanjut hapus
                        String deleteQuery = "DELETE FROM alat_lab WHERE kode_alat = ?";
                        PreparedStatement deleteStmt = conn.prepareStatement(deleteQuery);
                        deleteStmt.setString(1, idAlat);
                        int affectedRows = deleteStmt.executeUpdate();

                        if (affectedRows > 0) {
                            model.removeRow(row);
                            JOptionPane.showMessageDialog(this, "Data berhasil dihapus.");
                            clearForm();
                            setInitialState();
                            countData();
                        } else {
                            JOptionPane.showMessageDialog(this, "Data gagal dihapus dari database.");
                        }

                        deleteStmt.close();
                    }

                    rs.close();
                    cekStmt.close();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menghapus data.");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Silakan pilih data yang ingin dihapus.");
        }


    }//GEN-LAST:event_btnhapusActionPerformed

    
    private void btnkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkembaliActionPerformed
        // TODO add your handling code here:
        this.dispose(); // Tutup form saat ini

        // Buka form dashboard
        FrmDashboard dashboard = new FrmDashboard();
        dashboard.setVisible(true);
        dashboard.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnkembaliActionPerformed

    private void TampilData(){
        try {
            Connection conn = koneksi.GetConnection();
            java.sql.Statement stm = conn.createStatement();
            ResultSet sql = stm.executeQuery(
                "SELECT alat_lab.kode_alat, " +
                "alat_lab.nama, " +
                "alat_lab.username, " +
                "kategori.kode_kategori AS kategori, " +
                "alat_lab.satuan, " +
                "alat_lab.jumlah " +
                "FROM alat_lab " +
                "JOIN pj_lab ON alat_lab.username = pj_lab.username " +
                "JOIN kategori ON alat_lab.kode_kategori = kategori.kode_kategori"
            );


            
            daftarAlat.setModel(DbUtils.resultSetToTableModel(sql));
            daftarAlat.getColumnModel().getColumn(0).setPreferredWidth(40);
            daftarAlat.getColumnModel().getColumn(1).setPreferredWidth(90);
            daftarAlat.getColumnModel().getColumn(1).setPreferredWidth(90);
            daftarAlat.getColumnModel().getColumn(2).setPreferredWidth(45);
            daftarAlat.getColumnModel().getColumn(3).setPreferredWidth(70);
            daftarAlat.getColumnModel().getColumn(4).setPreferredWidth(7);

            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error " + e);
        }
    }
    
    private void GetData_View(){
        int row = daftarAlat.getSelectedRow();
        String row_kode = (daftarAlat.getModel().getValueAt(row, 0).toString());
        txtKode.setText(row_kode);
        BtnEnabled(true);
    }
    
    //membuat field kosong untuk add data
    private void TxtEmpty() {
        txtKode.setText("");
        txtNama.setText("");
        cmbPJLab.setSelectedIndex(0);
        cmbKategori.setSelectedIndex(0);
        txtJumlah.setText("");
        txtSatuan.setText(""); 
    }

    
    
    
    

    
    private void daftarAlatKeyReleased(java.awt.event.KeyEvent evt) {                                      
        // TODO add your handling code here:
        GetData_View();
    }                                     

    private void daftarAlatMouseReleased(java.awt.event.MouseEvent evt) {                                        
        // TODO add your handling code here:
//        GetData_View();
    }                                       

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        GetData();
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAlatLab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAlatLab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAlatLab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAlatLab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAlatLab().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnkembali;
    private javax.swing.JButton btnsave;
    private javax.swing.JComboBox<String> cmbKategori;
    private javax.swing.JComboBox<String> cmbPJLab;
    private javax.swing.JTable daftarAlat;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblJumlah;
    private javax.swing.JLabel lbl_action;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtKode;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtSatuan;
    // End of variables declaration//GEN-END:variables

    private void initUI() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void SelectKategori() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void GetData() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void BtnEnabled(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void executeQuery(String string) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

}
